// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: proto/employee.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_proto_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// Can add pagination here if needed later
type GetAllEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesRequest) Reset() {
	*x = GetAllEmployeesRequest{}
	mi := &file_proto_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesRequest) ProtoMessage() {}

func (x *GetAllEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{1}
}

type GetAllEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesResponse) Reset() {
	*x = GetAllEmployeesResponse{}
	mi := &file_proto_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesResponse) ProtoMessage() {}

func (x *GetAllEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_proto_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmployeeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_proto_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEmployeeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmployeeRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_proto_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEmployeeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmployeeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_proto_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEmployeeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_proto_employee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_employee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_employee_proto_rawDescGZIP(), []int{7}
}

func (x *EmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

var File_proto_employee_proto protoreflect.FileDescriptor

const file_proto_employee_proto_rawDesc = "" +
	"\n" +
	"\x14proto/employee.proto\x12\bemployee\"V\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"\x18\n" +
	"\x16GetAllEmployeesRequest\"K\n" +
	"\x17GetAllEmployeesResponse\x120\n" +
	"\temployees\x18\x01 \x03(\v2\x12.employee.EmployeeR\temployees\"$\n" +
	"\x12GetEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"S\n" +
	"\x15CreateEmployeeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"c\n" +
	"\x15UpdateEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"'\n" +
	"\x15DeleteEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"B\n" +
	"\x10EmployeeResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee2\xab\x03\n" +
	"\x0fEmployeeService\x12V\n" +
	"\x0fGetAllEmployees\x12 .employee.GetAllEmployeesRequest\x1a!.employee.GetAllEmployeesResponse\x12K\n" +
	"\x0fGetEmployeeByID\x12\x1c.employee.GetEmployeeRequest\x1a\x1a.employee.EmployeeResponse\x12M\n" +
	"\x0eCreateEmployee\x12\x1f.employee.CreateEmployeeRequest\x1a\x1a.employee.EmployeeResponse\x12Q\n" +
	"\x12UpdateEmployeeByID\x12\x1f.employee.UpdateEmployeeRequest\x1a\x1a.employee.EmployeeResponse\x12Q\n" +
	"\x12DeleteEmployeeByID\x12\x1f.employee.DeleteEmployeeRequest\x1a\x1a.employee.EmployeeResponseB\x16Z\x14employee/proto;protob\x06proto3"

var (
	file_proto_employee_proto_rawDescOnce sync.Once
	file_proto_employee_proto_rawDescData []byte
)

func file_proto_employee_proto_rawDescGZIP() []byte {
	file_proto_employee_proto_rawDescOnce.Do(func() {
		file_proto_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_employee_proto_rawDesc), len(file_proto_employee_proto_rawDesc)))
	})
	return file_proto_employee_proto_rawDescData
}

var file_proto_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_employee_proto_goTypes = []any{
	(*Employee)(nil),                // 0: employee.Employee
	(*GetAllEmployeesRequest)(nil),  // 1: employee.GetAllEmployeesRequest
	(*GetAllEmployeesResponse)(nil), // 2: employee.GetAllEmployeesResponse
	(*GetEmployeeRequest)(nil),      // 3: employee.GetEmployeeRequest
	(*CreateEmployeeRequest)(nil),   // 4: employee.CreateEmployeeRequest
	(*UpdateEmployeeRequest)(nil),   // 5: employee.UpdateEmployeeRequest
	(*DeleteEmployeeRequest)(nil),   // 6: employee.DeleteEmployeeRequest
	(*EmployeeResponse)(nil),        // 7: employee.EmployeeResponse
}
var file_proto_employee_proto_depIdxs = []int32{
	0, // 0: employee.GetAllEmployeesResponse.employees:type_name -> employee.Employee
	0, // 1: employee.EmployeeResponse.employee:type_name -> employee.Employee
	1, // 2: employee.EmployeeService.GetAllEmployees:input_type -> employee.GetAllEmployeesRequest
	3, // 3: employee.EmployeeService.GetEmployeeByID:input_type -> employee.GetEmployeeRequest
	4, // 4: employee.EmployeeService.CreateEmployee:input_type -> employee.CreateEmployeeRequest
	5, // 5: employee.EmployeeService.UpdateEmployeeByID:input_type -> employee.UpdateEmployeeRequest
	6, // 6: employee.EmployeeService.DeleteEmployeeByID:input_type -> employee.DeleteEmployeeRequest
	2, // 7: employee.EmployeeService.GetAllEmployees:output_type -> employee.GetAllEmployeesResponse
	7, // 8: employee.EmployeeService.GetEmployeeByID:output_type -> employee.EmployeeResponse
	7, // 9: employee.EmployeeService.CreateEmployee:output_type -> employee.EmployeeResponse
	7, // 10: employee.EmployeeService.UpdateEmployeeByID:output_type -> employee.EmployeeResponse
	7, // 11: employee.EmployeeService.DeleteEmployeeByID:output_type -> employee.EmployeeResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_employee_proto_init() }
func file_proto_employee_proto_init() {
	if File_proto_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_employee_proto_rawDesc), len(file_proto_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_employee_proto_goTypes,
		DependencyIndexes: file_proto_employee_proto_depIdxs,
		MessageInfos:      file_proto_employee_proto_msgTypes,
	}.Build()
	File_proto_employee_proto = out.File
	file_proto_employee_proto_goTypes = nil
	file_proto_employee_proto_depIdxs = nil
}
